services:
  postgres:
    image: postgres:16-alpine
    container_name: sprintly-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: sprintly
      POSTGRES_USER: sprintly
      POSTGRES_PASSWORD: sprintly
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: sprintly-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: sprintly
      RABBITMQ_DEFAULT_PASS: sprintly

volumes:
  pgdata: