spring.application.name=sprintly
spring.datasource.url=jdbc:postgresql://localhost:5433/sprintly
spring.datasource.username=sprintly
spring.datasource.password=sprintly
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-exception=false
jwt.secret=d10c323e98292bbafa9fd9c33642a7cbdd3c9078a5c24325ea3e2bca1e3562a54e53df3d68bee2f639ab086068e78bcf5d7c4a580e3d4c2ecc7819030c93d030
jwt.access-expiration=900000
jwt.refresh-expiration=2592000000