spring.application.name=sprintly
spring.datasource.url=jdbc:postgresql://localhost:5433/sprintly
spring.datasource.username=sprintly
spring.datasource.password=sprintly
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081